---
name: Analysis - Qodana

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
  merge_group:
  push:
    paths:
      - "src/**"
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: --compile-commands,./build/linux-debug/compile_commands.json,--baseline,qodana-base.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
